#include "cPlayerSpaceshipData.h"
#include "stdafx.h"
#include "MultiSpaceshipManager.h"
#include <Spore/Simulator/Serialization.h>

cMultiSpaceshipManager* cMultiSpaceshipManager::sInstance;

/// AUTOGENERATED METHODS ///

int cMultiSpaceshipManager::AddRef() {
    return Simulator::cStrategy::AddRef();
}
int cMultiSpaceshipManager::Release() {
    return Simulator::cStrategy::Release();
}

const char* cMultiSpaceshipManager::GetName() const {
    return "VanillaCold::MultiSpaceshipManager";
}

bool cMultiSpaceshipManager::Write(Simulator::ISerializerStream* stream)
{
    return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cMultiSpaceshipManager::Read(Simulator::ISerializerStream* stream)
{
    return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cMultiSpaceshipManager::ATTRIBUTES[] = {
    // Add more attributes here
    // This one must always be at the end
    SimAttribute(cMultiSpaceshipManager, mCurrentIndex, 1),
    SimAttribute(cMultiSpaceshipManager, mStoredSpaceships, 2),
    Simulator::Attribute(),
};

void cMultiSpaceshipManager::Initialize() {
    sInstance = this;
    mCurrentIndex = -1;
    mStoredSpaceships = vector<cPlayerSpaceshipDataPtr>();
}

void cMultiSpaceshipManager::Dispose() {

}

bool cMultiSpaceshipManager::WriteToXML(Simulator::XmlSerializer* writexml)
{
    return writexml->AttributesToXml(ATTRIBUTES, this, GetName());
}

void cMultiSpaceshipManager::OnModeEntered(uint32_t previousModeID, uint32_t newModeID)
{
    //if (newModeID == GameModeIDs::kGGEMode)
    //{
     //   mStoredSpaceships = vector<cPlayerSpaceshipDataPtr>();
      //  mCurrentIndex = -1;
    //}
    // do stuff
    ModAPI::Log("woaw");
    Simulator::cStrategy::OnModeEntered(previousModeID, newModeID);
}

void cMultiSpaceshipManager::Update(int deltaTime, int deltaGameTime) {

}


bool cMultiSpaceshipManager::SwitchSpaceship(int _index)
{
    if (_index == mCurrentIndex || _index >= mStoredSpaceships.size()
        || Simulator::SpacePlayerData::Get()->mCurrentContext != Simulator::SpaceContext::Galaxy)
    {
        return false;
    }

    auto ufo = Simulator::GetPlayerUFO();

    if (mCurrentIndex == -1)
    {
        mCurrentIndex = mStoredSpaceships.size();
        mStoredSpaceships.push_back(new cPlayerSpaceshipData());
    }
    cPlayerSpaceshipDataPtr _oldSpaceship = mStoredSpaceships[mCurrentIndex];
    _oldSpaceship->mbActive = false;
    _oldSpaceship->mPosition = Simulator::GetActiveStarRecord();
    _oldSpaceship->mHealth = ufo->mHealthPoints;
    _oldSpaceship->mEnergy = ufo->mEnergy;


    //vector<cSpaceInventoryItemPtr> _newItems;
    vector<cSpaceInventoryItemPtr> _otherItems;
    auto inv = SimulatorSpaceGame.mpPlayerInventory;
    for (cSpaceInventoryItemPtr itm : inv->mInventoryItems)
    {
        if (itm->mItemType != Simulator::SpaceInventoryItemType::Tool &&
            itm->mItemType != Simulator::SpaceInventoryItemType::CargoSlot &&
            itm->mItemType != Simulator::SpaceInventoryItemType::Unk7)
        {
            _otherItems.push_back(itm);
        }
    }

    for (cSpaceInventoryItemPtr itm : _otherItems)
    {
        inv->RemoveItem(itm.get());
    }

    auto& newShip = mStoredSpaceships[_index];
    for (cSpaceInventoryItemPtr itm : newShip->mCargoItems)
    {
        inv->AddItem(itm.get());
        //_newItems.push_back(itm);
    }

    _oldSpaceship->mCargoItems = _otherItems;
    //inv->mInventoryItems = _newItems;


    Simulator::SpaceTeleportTo(newShip->mPosition.get());

    ufo->mHealthPoints = newShip->mHealth;
    ufo->mEnergy = newShip->mEnergy;
    newShip->mbActive = true;

    mCurrentIndex = _index;

    return true;
}

uint32_t cMultiSpaceshipManager::CreateSpaceship()
{
    auto ufo = Simulator::GetPlayerUFO();
    //auto star = StarManager.GetStarRecord(GetPlayerEmpire()->mHomeStar);
    float _dist = 256;
    cStarRecordPtr closestStar = StarManager.GetStarRecord(Simulator::GetPlayerEmpire()->mHomeStar);
    cStarRecordPtr activeStar = Simulator::GetActiveStarRecord();

    for (cStarRecordPtr star : Simulator::GetPlayerEmpire()->mStars)
    {
        float _newDist = (star->mPosition - activeStar->mPosition).Length();
        if (_newDist < _dist)
        {
            closestStar = star;
            _dist = _newDist;
        }
    }

    int index = mStoredSpaceships.size();
    cPlayerSpaceshipDataPtr data = new cPlayerSpaceshipData();
    //mStoredSpaceships.push_back();

    //auto& _oldSpaceship = mStoredSpaceships[mCurrentIndex];
    data->mbActive = false;
    data->mPosition = closestStar;
    data->mHealth = ufo->mMaxHealthPoints;
    data->mEnergy = ufo->mMaxEnergy;

    mStoredSpaceships.push_back(data);
    return index;

}

bool cMultiSpaceshipManager::DestroySpaceship(bool _keepCargo)
{
    return false;
}

uint32_t cMultiSpaceshipManager::GetSpaceshipCount()
{
    return mStoredSpaceships.size();
}

uint32_t cMultiSpaceshipManager::GetActiveSpaceship()
{
    return mCurrentIndex;
}





cMultiSpaceshipManager* cMultiSpaceshipManager::Get()
{
    return sInstance;
}
