#include "stdafx.h"
#include "MultiSpaceshipManager.h"
#include <Spore/Simulator/Serialization.h>

MultiSpaceshipManager* MultiSpaceshipManager::sInstance;

/// AUTOGENERATED METHODS ///

int MultiSpaceshipManager::AddRef() {
    return Simulator::cStrategy::AddRef();
}
int MultiSpaceshipManager::Release() {
    return Simulator::cStrategy::Release();
}

const char* MultiSpaceshipManager::GetName() const {
    return "VanillaCold::MultiSpaceshipManager";
}

bool MultiSpaceshipManager::Write(Simulator::ISerializerStream* stream)
{
    return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool MultiSpaceshipManager::Read(Simulator::ISerializerStream* stream)
{
    return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute MultiSpaceshipManager::ATTRIBUTES[] = {
    // Add more attributes here
    // This one must always be at the end
    //SimAttribute(MultiSpaceshipManager,Selection,1),
    SimAttribute(MultiSpaceshipManager, mCurrentIndex, 2),
    SimAttribute(MultiSpaceshipManager, mStoredSpaceships, 1),
    Simulator::Attribute()
};

void MultiSpaceshipManager::Initialize() {
    sInstance = this;
}

void MultiSpaceshipManager::Dispose() {
    sInstance = nullptr;
}

void MultiSpaceshipManager::Update(int deltaTime, int deltaGameTime) {
    // do suff
}

bool MultiSpaceshipManager::WriteToXML(Simulator::XmlSerializer* writexml)
{
    return false;
}

void MultiSpaceshipManager::OnModeEntered(uint32_t previousModeID, uint32_t newModeID)
{
    // do stuff
}




bool MultiSpaceshipManager::SwitchSpaceship(int _index)
{
    if (_index == mCurrentIndex || _index >= mStoredSpaceships.size()
        || Simulator::SpacePlayerData::Get()->mCurrentContext != Simulator::SpaceContext::Galaxy)
    {
        return false;
    }

    auto ufo = Simulator::GetPlayerUFO();

    if (mCurrentIndex == -1)
    {
        mCurrentIndex = mStoredSpaceships.size();
        mStoredSpaceships.push_back(PlayerSpaceshipData());
    }
    auto& _oldSpaceship = mStoredSpaceships[mCurrentIndex];
    _oldSpaceship.mbActive = false;
    _oldSpaceship.mPosition = Simulator::GetActiveStarRecord();
    _oldSpaceship.mHealth = ufo->mHealthPoints;
    _oldSpaceship.mEnergy = ufo->mEnergy;


    vector<cSpaceInventoryItemPtr> _newItems;
    vector<cSpaceInventoryItemPtr> _otherItems;
    auto inv = SimulatorSpaceGame.mpPlayerInventory;
    for (cSpaceInventoryItemPtr itm : inv->mInventoryItems)
    {
        if (itm->mItemType == Simulator::SpaceInventoryItemType::Tool)
        {
            _newItems.push_back(itm);
        }
        else
        {
            _otherItems.push_back(itm);
        }
    }
    auto& newShip = mStoredSpaceships[_index];
    for (cSpaceInventoryItemPtr itm : newShip.mCargoItems)
    {
        _newItems.push_back(itm);
    }

    _oldSpaceship.mCargoItems = _otherItems;
    inv->mInventoryItems = _newItems;

    ufo->mHealthPoints = newShip.mHealth;
    ufo->mEnergy = newShip.mEnergy;
    newShip.mbActive = true;
    Simulator::SpaceTeleportTo(newShip.mPosition.get());

    return true;
}

int MultiSpaceshipManager::CreateSpaceship()
{
    auto ufo = Simulator::GetPlayerUFO();
    //auto star = StarManager.GetStarRecord(GetPlayerEmpire()->mHomeStar);
    float _dist = 256;
    cStarRecordPtr closestStar = StarManager.GetStarRecord(Simulator::GetPlayerEmpire()->mHomeStar);
    cStarRecordPtr activeStar = Simulator::GetActiveStarRecord();

    for (cStarRecordPtr star : Simulator::GetPlayerEmpire()->mStars)
    {
        float _newDist = (star->mPosition - activeStar->mPosition).Length();
        if (_newDist < _dist)
        {
            closestStar = star;
            _dist = _newDist;
        }
    }

    int index = mStoredSpaceships.size();
    auto data = PlayerSpaceshipData();
    //mStoredSpaceships.push_back();

    //auto& _oldSpaceship = mStoredSpaceships[mCurrentIndex];
    data.mbActive = false;
    data.mPosition = closestStar;
    data.mHealth = ufo->mMaxHealthPoints;
    data.mEnergy = ufo->mMaxEnergy;

    mStoredSpaceships.push_back(data);

}

bool MultiSpaceshipManager::DestroySpaceship(bool _keepCargo)
{

}





MultiSpaceshipManager* MultiSpaceshipManager::Get()
{
    return sInstance;
}
